### ISSUE TITLE
[BUG] Index settings sync from leader fails for Remote Store enabled follower 

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/cross-cluster-replication#1300]
**What is the bug?**
While index settings are being synced from leader domain(OS1.3) to follower domain(OS_2.11 | Remote Store) , we get the following error

```
[2023-12-11T19:03:20,322][INFO ][o.o.r.t.i.IndexReplicationTask] [bba39cc188fdc55b7516a083b0f7b5ad] [aggregate_email_event_automation] Closed the index aggregate_email_event_automation to apply static settings now
[2023-12-11T19:03:20,385][INFO ][o.o.g.r.RemoteClusterStateService] [bba39cc188fdc55b7516a083b0f7b5ad] writing cluster state for version [143] took [60ms]; wrote metadata for [1] indices and skipped [8] unchanged indices, global metadata updated : [false]
[2023-12-11T19:03:20,433][INFO ][o.o.p.PluginsService     ] [bba39cc188fdc55b7516a083b0f7b5ad] PluginService:onIndexModule index:[aggregate_email_event_automation/01ayit5a7KRtaDUCmA4ImcBQ]
[2023-12-11T19:03:20,612][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [bba39cc188fdc55b7516a083b0f7b5ad] Detected cluster change event for destination migration
[2023-12-11T19:03:20,613][ERROR][o.o.r.m.TransportUpdateMetadataAction] [bba39cc188fdc55b7516a083b0f7b5ad] failed to update settings on index aggregate_email_event_automation
java.lang.IllegalArgumentException: final aggregate_email_event_automation setting [index.replication.type], not updateable
        at org.opensearch.common.settings.AbstractScopedSettings.updateSettings(AbstractScopedSettings.java:871)
        at org.opensearch.common.settings.AbstractScopedSettings.updateSettings(AbstractScopedSettings.java:824)
        at org.opensearch.cluster.metadata.MetadataUpdateSettingsService$1.execute(MetadataUpdateSettingsService.java:300)
        at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:65)
        at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:880)
        at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:432)
        at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:299)
        at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:210)
        at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:209)
        at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:247)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:858)
        at [2023-12-11T19:03:20,616][INFO ][o.o.c.m.MetadataIndexStateService] [bba39cc188fdc55b7516a083b0f7b5ad] opening indices [[aggregate_email_event_automation/01ayit5a7KRtaDUCmA4ImcBQ]]
```

It seems the issue happens due to a settings which is supported on follower but not on leader domain. During index settings sync such settings value may come as null since leader doesn't support it.

Another reason this could happen is if leader support setting the value of a setting as some value which is not supported in the follower domain. in the case of index.replication.type setting, leader could support setting it to null to allow it to fallback to the default value. But in the follower domain(Remote Store) we dont allow it to be set to null

Also, when this setting application fails, we still proceed and open the index.

https://github.com/opensearch-project/cross-cluster-replication/blob/be24bfaa9a795179662a6660633902a7737b717c/src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt#L619-L634

**What is the expected behavior?**
Such index sync operations should be handled gracefully.

**Comment by nisgoel-amazon** [comment]
@monusingh-1  Assign this to me

**Comment by monusingh-1** [comment]
Thanks @nisgoel-amazon for closing this.
