### ISSUE TITLE
[BUG] Security Test CI workflow failing due to plugin build failure

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/cross-cluster-replication#308]
**Describe the bug**
Security Test CI workflow failing due to plugin build failure

**To Reproduce**
Check latest errors on: 
- https://github.com/opensearch-project/cross-cluster-replication/runs/5269544238?check_suite_focus=true
```
Run mvn clean package -Padvanced -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.0[9](https://github.com/opensearch-project/cross-cluster-replication/runs/5269544238?check_suite_focus=true#step:5:9)9 s
[INFO] Finished at: 2022-02-21T05:[14](https://github.com/opensearch-project/cross-cluster-replication/runs/5269544238?check_suite_focus=true#step:5:14):02Z
[INFO] ------------------------------------------------------------------------
Warning:  The requested profile "advanced" could not be activated because it does not exist.
Error:  The goal you specified requires a project to execute but there is no POM in this directory (/home/runner/work/cross-cluster-replication/cross-cluster-replication/security). Please verify you invoked Maven from the correct directory. -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
Error: Process completed with exit code 1.
```

**Expected behavior**
The security plugin build should have succeeded in CI workflow

**Comment by saikaranam-amazon** [comment]
security plugin updated to gradle based build system.
Raising PR to update the build for security plugin

**Comment by saikaranam-amazon** [comment]
Seeing another error after updating the build steps:

```
Exception in thread "main" java.lang.IllegalArgumentException: illegal version format - snapshot labels are not supported
| 	at org.opensearch.Version.fromStringSlow(Version.java:201)
| 	at org.opensearch.Version.fromString(Version.java:196)
| 	at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:252)
| 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:799)
| 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:858)
| 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
| 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
| 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
| 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
| 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
| 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
| 	at org.opensearch.cli.Command.main(Command.java:101)
| 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

**Comment by saikaranam-amazon** [comment]
Issue tracking at OpenSearch end: https://github.com/opensearch-project/opensearch-build/issues/359
With movement to gradle based build system. Security plugin is updating plugin descriptor files to contain "-SNAPSHOT" for the OpenSearch version.
