### ISSUE TITLE
Add support for gradle 7 in the plugin.

### ISSUE THREAD

**Issue by naveenpajjuri** [opensearch-project/cross-cluster-replication#328]
**Describe the bug**
Plugin doesn't compile with JDK 17, as we require Gradle 7 for JDK 17. it fails with below stack trace.

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'opensearch-cross-cluster-replication'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:68)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$600(LifecycleProjectEvaluator.java:51)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject$1.run(LifecycleProjectEvaluator.java:104)
        at org.gradle.internal.Factories$1.create(Factories.java:26)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:180)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withProjectLock(DefaultProjectStateRegistry.java:271)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:265)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:226)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:91)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.i
        
        
        
        




aused by: org.gradle.cache.CacheOpenException: Could not open proj generic class cache for build file '/Volumes/workplace/cross-cluster-replication/build.gradle' (/Users/nppajjur/.gradle/caches/6.6.1/scripts/5j29jy24xbv4x4oi83cnxd51z).
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:80)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:42)
```

**Expected Behavior**
Plugin should build with JDK 17.

**Plugins**
[cross-cluster-replication](https://github.com/opensearch-project/cross-cluster-replication)

**Comment by naveenpajjuri** [comment]
Failure Stacktrace with gradle 7

```
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
build file '/Volumes/workplace/cross-cluster-replication/build.gradle': 442: unable to resolve class GroovyMBean 
 @ line 442, column 35.
                   def jacocoMBean = new GroovyMBean(connector.MBeanServerConnection, "org.jacoco:type=Runtime")
                                     ^

1 error

        at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.compileScript(DefaultScriptCompilationHandler.java:139)

```

**Comment by naveenpajjuri** [comment]
This is done as part of 2.0
