### ISSUE TITLE
[BUG] Intermittent Integration test failure in GetChanges API on leader cluster

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/cross-cluster-replication#459]
**What is the bug?**
Intermittent test failure observed in one of the run
```
[ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [leaderCluster-0] fatal error in thread [opensearch[leaderCluster-0][replication_leader][T#4] @coroutine#63], exiting
java.lang.AssertionError: Checkpoint didn't advance at all
	at org.opensearch.replication.action.changes.TransportGetChangesAction$asyncShardOperation$1.invokeSuspend(TransportGetChangesAction.kt:92) ~[opensearch-cross-cluster-replication-2.1.0.0-SNAPSHOT.jar:2.1.0.0-SNAPSHOT]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:739) [opensearch-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by ankitkala** [comment]
So far we haven't seen this issue again. Well prioritise this incase we see more occurrences
