### ISSUE TITLE
Remove dependency on BaseNodeRequest for stat APIs

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#600]
CCR plugin build for 3.0 version fails with following error:
```
> Task :compileKotlin FAILED
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/NodeStatsRequest.kt: (14, 44): Unresolved reference: BaseNodeRequest
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/NodeStatsRequest.kt: (19, 26): Unresolved reference: BaseNodeRequest
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/NodeStatsRequest.kt: (21, 43): Too many arguments for public constructor Any() defined in kotlin.Any
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/NodeStatsRequest.kt: (26, 5): 'writeTo' overrides nothing
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/NodeStatsRequest.kt: (27, 15): Unresolved reference: writeTo
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/TransportFollowerStatsAction.kt: (37, 75): Type argument is not within its bounds: should be subtype of 'TransportRequest!'
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/TransportFollowerStatsAction.kt: (38, 103): Callable reference resolution ambiguity: 
public constructor NodeStatsRequest() defined in org.opensearch.replication.action.stats.NodeStatsRequest
public constructor NodeStatsRequest(inp: StreamInput) defined in org.opensearch.replication.action.stats.NodeStatsRequest
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/TransportLeaderStatsAction.kt: (39, 71): Type argument is not within its bounds: should be subtype of 'TransportRequest!'
e: /Volumes/ws/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/stats/TransportLeaderStatsAction.kt: (40, 101): Callable reference resolution ambiguity: 
public constructor NodeStatsRequest() defined in org.opensearch.replication.action.stats.NodeStatsRequest
public constructor NodeStatsRequest(inp: StreamInput) defined in org.opensearch.replication.action.stats.NodeStatsRequest
```

Looks like we've extended `BaseNodeRequest` for our stats APIs which has been removed [here](https://github.com/opensearch-project/OpenSearch/commit/fe3994ccdf62735907bc4834f93c71d97636d150#diff-a8affa0470501c9cb284bfbd66f00d493fc72bf05d12e4e2c89bfda6fe814371). 

We need to refactor the implementation and move away from these deprecated dependencies for 3.0

Related issue for 3.0 bump: https://github.com/opensearch-project/cross-cluster-replication/issues/451

**Comment by ankitkala** [comment]
https://github.com/opensearch-project/OpenSearch/issues/4938

**Comment by ankitkala** [comment]
After removing the references to `BaseNodeRequest ` in [this PR](https://github.com/opensearch-project/cross-cluster-replication/pull/556), integration tests are failing locally with following error: 
```
ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [leaderCluster-0] fatal error in thread [Thread-6], exiting
»  java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract org.opensearch.action.support.nodes.BaseNodeRequest newNodeRequest(org.opensearch.action.support.nodes.BaseNodesRequest)' of abstract class org.opensearch.action.support.nodes.TransportNodesAction.
»       at org.opensearch.action.support.nodes.TransportNodesAction$AsyncAction.start(TransportNodesAction.java:259) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:153) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:70) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:434) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:741) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.replication.rest.LeaderStatsHandler.prepareRequest$lambda-0(LeaderStatsHandler.kt:40) ~[?:?]
»       at org.opensearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:126) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.rest.RestController.dispatchRequest(RestController.java:312) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.rest.RestController.tryAllHandlers(RestController.java:398) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.rest.RestController.dispatchRequest(RestController.java:241) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:366) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:445) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:356) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»       at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:55) ~[?:?]
»       at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:41) ~[?:?]
»       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at org.opensearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:71) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
»       at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:242) ~[?:?]
»       at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:40) ~[?:?]
»       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[?:?]
»       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[?:?]
»       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[?:?]
»       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
»       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
»       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
»       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
»       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
»       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[?:?]
»       at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) ~[?:?]
»       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) ~[?:?]
»       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[?:?]
»       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
»       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
»       at java.lang.Thread.run(Thread.java:832) [?:?]
```


However I'm not seeing this issue with github CI workflow and the plugin compilation failed with the error below. Its not able to resolve the `org.apache.http` package 
```
/home/runner/work/cross-cluster-replication/cross-cluster-replication/src/test/kotlin/org/opensearch/replication/MultiClusterRestTestCase.kt: (19, 19): Unresolved reference: http
```

**Comment by ankitkala** [comment]
Need to bump apache http client to 5.x:  https://github.com/opensearch-project/OpenSearch/pull/4459/files

**Comment by ankitkala** [comment]
https://github.com/opensearch-project/cross-cluster-replication/pull/556
