### ISSUE TITLE
[BUG] Fix BWC tests on 3.0

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#620]
Currently BWC tests are failing on OS 3.0: https://github.com/opensearch-project/cross-cluster-replication/actions/runs/3359666773/jobs/5567932617

Basically the cluster went unresponsive after upgrading one of the nodes. Though It doesn't seem to be related to CCR, we still need to triage this once and identify the root cause.

**Comment by ankitkala** [comment]
I tried taking a look again. Rolling upgrade tests are failing. After the first node is upgraded to 3.0, node is unable to join master. I can also see that master node also freezes(process is up and but no logs). Here are the logs: 

`bwcLeader0-0` is the node that upgraded. Logs: 
```
[2023-04-17T18:44:47,502][WARN ][o.o.c.c.ClusterFormationFailureHelper] [bwcLeader0-0] cluster-manager not discovered or elected yet, an election requires at least 2 nodes with ids from [f2Qc2CtRR52qi0lOxoNWLA, na_iUH4eS0G4YMXdXyUGNQ, Yl5_pcSoTtOB_HjAXH8pdA], have discovered [{bwcLeader0-0}{f2Qc2CtRR52qi0lOxoNWLA}{wuDkRrwZTqmkauQ9D7hw4Q}{127.0.0.1}{127.0.0.1:51544}{dimr}{upgraded=true, testattr=test, shard_indexing_pressure_enabled=true}] which is not a quorum; discovery will continue using [[::1]:51318, 127.0.0.1:51319, [::1]:51323, 127.0.0.1:51324] from hosts providers and [{bwcLeader0-0}{f2Qc2CtRR52qi0lOxoNWLA}{wuDkRrwZTqmkauQ9D7hw4Q}{127.0.0.1}{127.0.0.1:51544}{dimr}{upgraded=true, testattr=test, shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 5, last-accepted version 12 in term 5
[2023-04-17T18:44:47,765][WARN ][r.suppressed             ] [bwcLeader0-0] path: /_cluster/health, params: {wait_for_status=yellow, wait_for_nodes=>=3}
org.opensearch.discovery.ClusterManagerNotDiscoveredException: null
	at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction$2.onTimeout(TransportClusterManagerNodeAction.java:350) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:394) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:294) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:707) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

`bwcLeader0-1`(Master node):
```
[2023-04-17T18:43:42,886][INFO ][o.o.c.c.FollowersChecker ] [bwcLeader0-1] FollowerChecker{discoveryNode={bwcLeader0-0}{f2Qc2CtRR52qi0lOxoNWLA}{D2WPoAw3RfuXZVIj8_qQ5Q}{127.0.0.1}{127.0.0.1:51219}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, failureCountSinceLastSuccess=0, [cluster.fault_detection.follower_check.retry_count]=3} marking node as faulty
[2023-04-17T18:43:42,894][INFO ][o.o.c.s.MasterService    ] [bwcLeader0-1] node-left[{bwcLeader0-0}{f2Qc2CtRR52qi0lOxoNWLA}{D2WPoAw3RfuXZVIj8_qQ5Q}{127.0.0.1}{127.0.0.1:51219}{dimr}{testattr=test, shard_indexing_pressure_enabled=true} reason: disconnected], term: 5, version: 13, delta: removed {{bwcLeader0-0}{f2Qc2CtRR52qi0lOxoNWLA}{D2WPoAw3RfuXZVIj8_qQ5Q}{127.0.0.1}{127.0.0.1:51219}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}
[2023-04-17T18:43:42,896][DEBUG][o.o.c.c.PublicationTransportHandler] [bwcLeader0-1] received diff cluster state version [13] with uuid [iYjVAg3jRhyWjpUuFituvg], diff size [656]
[2023-04-17T18:43:42,963][INFO ][o.o.c.s.ClusterApplierService] [bwcLeader0-1] removed {{bwcLeader0-0}{f2Qc2CtRR52qi0lOxoNWLA}{D2WPoAw3RfuXZVIj8_qQ5Q}{127.0.0.1}{127.0.0.1:51219}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}, term: 5, version: 13, reason: Publication{term=5, version=13}
[2023-04-17T18:43:42,984][INFO ][o.o.c.r.DelayedAllocationService] [bwcLeader0-1] scheduling reroute for delayed shards in [59.9s] (1 delayed shards)
[2023-04-17T18:43:42,984][DEBUG][o.o.c.c.C.CoordinatorPublication] [bwcLeader0-1] publication ended successfully: Publication{term=5, version=13}
[2023-04-17T18:43:43,024][INFO ][o.o.i.s.IndexShard       ] [bwcLeader0-1] [bwc_test_index][0] primary-replica resync completed with 0 operations
[2023-04-17T18:44:42,894][DEBUG][o.o.c.c.PublicationTransportHandler] [bwcLeader0-1] received diff cluster state version [14] with uuid [rbON9BKfQFuFu_IbQJds_A], diff size [318]
[2023-04-17T18:44:43,050][DEBUG][o.o.c.c.C.CoordinatorPublication] [bwcLeader0-1] publication ended successfully: Publication{term=5, version=14}
[2023-04-17T18:44:43,084][WARN ][o.o.c.r.a.AllocationService] [bwcLeader0-1] [bwc_test_index][0] marking unavailable shards as stale: [mVtF80e6QTSoqiazZMeFwA]
[2023-04-17T18:44:43,086][DEBUG][o.o.c.c.PublicationTransportHandler] [bwcLeader0-1] received diff cluster state version [15] with uuid [vtOX4DfxRdeKHdW7JWWJ7w], diff size [433]
[2023-04-17T18:44:43,149][DEBUG][o.o.c.c.C.CoordinatorPublication] [bwcLeader0-1] publication ended successfully: Publication{term=5, version=15}
[2023-04-17T18:44:43,404][INFO ][o.o.i.r.RecoverySourceHandler] [bwcLeader0-1] [bwc_test_index][0][recover to bwcLeader0-2] finalizing recovery took [120.8ms]
[2023-04-17T18:44:43,407][INFO ][o.o.c.r.a.AllocationService] [bwcLeader0-1] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[bwc_test_index][0]]]).
[2023-04-17T18:44:43,408][DEBUG][o.o.c.c.PublicationTransportHandler] [bwcLeader0-1] received diff cluster state version [16] with uuid [IZpKNhjoSDGs8-2xSmIywQ], diff size [485]
[2023-04-17T18:44:43,455][DEBUG][o.o.c.c.C.CoordinatorPublication] [bwcLeader0-1] publication ended successfully: Publication{term=5, version=16}
```

Logs from 3rd node `bwcLeader0-2`
```
[2023-04-17T18:43:42,962][INFO ][o.o.c.s.ClusterApplierService] [bwcLeader0-2] removed {{bwcLeader0-0}{f2Qc2CtRR52qi0lOxoNWLA}{D2WPoAw3RfuXZVIj8_qQ5Q}{127.0.0.1}{127.0.0.1:51219}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}, term: 5, version: 13, reason: ApplyCommitRequest{term=5, version=13, sourceNode={bwcLeader0-1}{na_iUH4eS0G4YMXdXyUGNQ}{ieUCKHmrQnGBXRfMiOtXNQ}{127.0.0.1}{127.0.0.1:51319}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}
[2023-04-17T18:44:42,896][DEBUG][o.o.c.c.PublicationTransportHandler] [bwcLeader0-2] received diff cluster state version [14] with uuid [rbON9BKfQFuFu_IbQJds_A], diff size [318]
[2023-04-17T18:44:42,962][INFO ][o.o.p.PluginsService     ] [bwcLeader0-2] PluginService:onIndexModule index:[bwc_test_index/d9Mf4r26S92WNkr9jmINrA]
[2023-04-17T18:44:43,087][DEBUG][o.o.c.c.PublicationTransportHandler] [bwcLeader0-2] received diff cluster state version [15] with uuid [vtOX4DfxRdeKHdW7JWWJ7w], diff size [433]
[2023-04-17T18:44:43,409][DEBUG][o.o.c.c.PublicationTransportHandler] [bwcLeader0-2] received diff cluster state version [16] with uuid [IZpKNhjoSDGs8-2xSmIywQ], diff size [485]
[2023-04-17T18:44:47,885][DEBUG][o.o.c.c.LeaderChecker    ] [bwcLeader0-2] leader [{bwcLeader0-1}{na_iUH4eS0G4YMXdXyUGNQ}{ieUCKHmrQnGBXRfMiOtXNQ}{127.0.0.1}{127.0.0.1:51319}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}] disconnected
[2023-04-17T18:44:47,885][INFO ][o.o.c.c.Coordinator      ] [bwcLeader0-2] cluster-manager node [{bwcLeader0-1}{na_iUH4eS0G4YMXdXyUGNQ}{ieUCKHmrQnGBXRfMiOtXNQ}{127.0.0.1}{127.0.0.1:51319}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}] failed, restarting discovery
org.opensearch.transport.NodeDisconnectedException: [bwcLeader0-1][127.0.0.1:51319][disconnected] disconnected
[2023-04-17T18:44:47,886][DEBUG][o.o.c.c.Coordinator      ] [bwcLeader0-2] onLeaderFailure: coordinator becoming CANDIDATE in term 5 (was FOLLOWER, lastKnownLeader was [Optional[{bwcLeader0-1}{na_iUH4eS0G4YMXdXyUGNQ}{ieUCKHmrQnGBXRfMiOtXNQ}{127.0.0.1}{127.0.0.1:51319}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}]])
[2023-04-17T18:44:47,886][INFO ][o.o.c.s.ClusterApplierService] [bwcLeader0-2] cluster-manager node changed {previous [{bwcLeader0-1}{na_iUH4eS0G4YMXdXyUGNQ}{ieUCKHmrQnGBXRfMiOtXNQ}{127.0.0.1}{127.0.0.1:51319}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}], current []}, term: 5, version: 16, reason: becoming candidate: onLeaderFailure
```

**Comment by ankitkala** [comment]
Disabling the `mixedClusterTask` for 3.0 now: 

https://github.com/opensearch-project/opensearch-plugins/issues/167
https://github.com/opensearch-project/job-scheduler/pull/242/files
