### ISSUE TITLE
[BUG] Dynamic Mapping is not updating when replicating index from 1.x to 2.x

### ISSUE THREAD

**Issue by nisgoel-amazon** [opensearch-project/cross-cluster-replication#758]
**What is the bug?**
When we start replication from 1.x domain to 2.x domain, it starts replicating index from leader to follower domain. But when we load new doc type data whose type is different from previous one in leader, then that data is not getting replicated on follower domain.

**How can one reproduce the bug?**
1. Create an index on leader with name `test-index` on leader domain with version 1.3
2. Load data with doc 
```
curl -k -XPOST -u $CREDS "https://$LEADER/test-index/type1/1?pretty" -H 'Content-Type: application/json' -d '                                                                   
{ "description": "test1" }
'
```
3. Start replication on follower with _start API, verify data is replicated on follower 
4. Now load data on leader with different doc field 
```
curl -k -XPOST -u $CREDS "https://$LEADER/test-index/type1/2?pretty" -H 'Content-Type: application/json' -d '                                                   
{ "title": "new-test" }
'
```
5. This data is not replicated to follower
6. Error in logs is coming as
```
ransportSerializationException[Failed to deserialize response from handler [org.opensearch.transport.TransportService$ContextRestoreResponseHandler/org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler@774617bd]]; nested: IllegalStateException[Expected _doc but got [type1]];
        at org.opensearch.transport.InboundHandler.handleResponse(InboundHandler.java:375)
        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:160)
        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:114)
        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:769)
        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175)
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150)
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115)
        at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)        at 
```
**What is the expected behavior?**
Expected behavior is that, new doc should also get replicated to Follower Domain

**Comment by sricharanvuppu** [comment]
From 2.x versions only `_doc` type is allowed. To perform replication from 1.x to 2.x, reindex to type `_doc` and start replication. This will be handled in Amazon OpenSearch (AOS)

**Comment by monusingh-1** [comment]
Thanks for the update @sricharanvuppu , closing this issue.
