### ISSUE TITLE
[BUG] Auto follow stopped working

### ISSUE THREAD

**Issue by laszloszurok** [opensearch-project/cross-cluster-replication#840]
**What is the bug?**
I set up CCR auto follow based on the official docs. Initially the replication worked, but after a while (~3 days) I noticed that new leaders are not replicated. I am able to start replication on those indices by calling the `_plugins/_replication/follower-index/_start` API manually.

Also it looks like the auto follow operation tries to work with indices that got deleted already. Some lines from my OpenSearch logs for example:

```
[2023-05-19T12:31:52,987][ERROR][o.o.r.a.i.TransportReplicateIndexClusterManagerNodeAction] [oszto-log-01b] Failed to trigger replication for site-a-oszto-alerting-000038 - ResourceAlreadyExistsException[task with id {replication:index:site-a-oszto-alerting-000038} already exist]

[2023-05-19T12:31:52,952][WARN ][o.o.r.t.a.AutoFollowTask ] [oszto-log-03b][site-a] Failed to start replication for site-a:site-a-oszto-alerting-000037 -> site-a-oszto-alerting-000037.

org.opensearch.ResourceAlreadyExistsException: task with id {replication:index:site-a-oszto-alerting-000037} already exist

[2023-05-19T12:31:52,952][WARN ][o.o.r.t.a.AutoFollowTask ] [oszto-log-03b][site-a] Failed to start replication for site-a:site-a-oszto-alerting-000037 -> site-a-oszto-alerting-000037.

org.opensearch.ResourceAlreadyExistsException: task with id {replication:index:site-a-oszto-alerting-000037} already exist

org.opensearch.ResourceAlreadyExistsException: task with id {replication:index:site-a-oszto-agent-000038} already exist

[2023-05-19T12:31:52,932][WARN ][o.o.r.t.a.AutoFollowTask ] [oszto-log-03b][site-a] Failed to start replication for site-a:site-a-oszto-agent-000038 -> site-a-oszto-agent-000038.

[2023-05-19T12:31:52,932][WARN ][o.o.r.t.a.AutoFollowTask ] [oszto-log-03b][site-a] Failed to start replication for site-a:site-a-oszto-agent-000038 -> site-a-oszto-agent-000038.
```

I deleted and recreated the auto follow pattern multiple times during my setup and also stopped replication for all indices, deleted them and restarted the auto follow. Then I started to discover the issues above.

While trying to debug this I tried to see active tasks in the cluster:
`GET _cat/tasks?v&actions=*replication*&detailed`
This call returns a non-empty list even after I stopped replication on my indices. I don't know if this should be the case.

This issue looks similar to mine: #202

Calling `GET /_plugins/_replication/follower_stats` I am able to see the active replicating follower indices. Seemingly there are a bunch of indices in bootstrapping state:
```
  "num_syncing_indices" : 2,
  "num_bootstrapping_indices" : 10,
  "num_paused_indices" : 1,
  "num_failed_indices" : 2,
```

I would appreciate some help and directions as I had no luck searching the docs and the forum.

**environment**
OpenSearch 2.4 running in docker

**Comment by defesteban** [comment]
Hi!
We have the same problem on `1.3.7` OpenSearch version.
Replication is not started for all our indices with the following error:
```
[2023-05-18T12:03:27,684][WARN ][o.o.r.t.a.AutoFollowTask ] [opensearch-0][leader-cluster] Failed to start replication for leader-cluster:7ef4f9de-eba0-4a3d-a3ef-e7a9459eecda_test -> 7ef4f9de-eba0-4a3d-a3ef-e7a9459eecda_test.
org.opensearch.ResourceAlreadyExistsException: task with id {replication:index:7ef4f9de-eba0-4a3d-a3ef-e7a9459eecda_test} already exist
	at org.opensearch.persistent.PersistentTasksClusterService$1.execute(PersistentTasksClusterService.java:135) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:63) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:804) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:378) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:249) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.service.MasterService.access$000(MasterService.java:86) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:173) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:174) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:212) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733) [opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:275) ~[opensearch-1.3.7.jar:1.3.7]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:238) ~[opensearch-1.3.7.jar:1.3.7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
Restarting `autofollow` replication (with removing all indices replication) does not help.
The tasks list (GET _cat/tasks?v) contains information only about `autofollow` task:
```
action                                          task_id                        parent_task_id                 type       start_time    timestamp r
unning_time ip           node
cluster:admin/plugins/replication/autofollow[c] dyMcPCIdSf2G-dBbz13o2w:1134336 cluster:6044                   persistent 1684412109794 12:15:09  4
.8m         10.202.0.197 opensearch-0
cluster:monitor/tasks/lists                     dyMcPCIdSf2G-dBbz13o2w:1135496 -                              transport  1684412399978 12:19:59  5
89.9micros  10.202.0.197 opensearch-0
cluster:monitor/tasks/lists[n]                  dyMcPCIdSf2G-dBbz13o2w:1135497 dyMcPCIdSf2G-dBbz13o2w:1135496 direct     1684412399978 12:19:59  2
23.1micros  10.202.0.197 opensearch-0
cluster:monitor/tasks/lists[n]                  BnTrLhJzTbitwVhX4tqsjg:1072391 dyMcPCIdSf2G-dBbz13o2w:1135496 transport  1684412399980 12:19:59  4
97.4micros  10.202.3.202 opensearch-2
cluster:monitor/tasks/lists[n]                  sgCqBy8rT1mj8Hh2FX5Q2w:1506489 dyMcPCIdSf2G-dBbz13o2w:1135496 transport  1684412399980 12:19:59  5
37.3micros  10.202.1.47  opensearch-1
```
It looks like the previous tasks are cached in persistent storage, because restarting of OpenSearch pods doesn't help either. But completely clearing persistent storage for all OpenSearch nodes solves the problem.

We couldn't find the answer in OpenSearch `_state` files, but the problem seems to be there. We would appreciate explanation of this behaviour and permanent fix without deleting data.

**Comment by nisgoel-amazon** [comment]
@laszloszurok @defesteban Thank you for raising this issue, we have recently identified this issue and working on clearing these persistent task from cluster state.

But can you please check in the logs error for not clearing that persistent task from the cluster state and share with us.
This might happen at the time of index went auto pause or replication was stopped intentionally at some time, there should be some error log why this cluster state is not cleared at that moment.

**Comment by ankitkala** [comment]
Can you try cancelling the task using task api? That should help in clearing the older task. 

`curl -XPOST localhost:9200/_tasks/pgEtYiv4TV-FsobOo5Sj0Q:40184/_cancel -d {} -H 'Content-Type: application/json'`

This is the tracking task for the fix: https://github.com/opensearch-project/cross-cluster-replication/issues/571

**Comment by defesteban** [comment]
Hi!

Could you please explain why this bug is closed with `completed` state?

Also we face the same problem now, we can't find the task ID to try to remove it manually. Could you explain where we can find it, because I can see only action in the error:
```
[2023-06-19T12:37:32,245][ERROR][o.o.r.a.i.TransportReplicateIndexMasterNodeAction] [opensearch-1] Failed to trigger replication for opensearch_metadata - ResourceAlreadyExistsException[task with id {replication:index:opensearch_metadata} already exist]
	at org.opensearch.persistent.PersistentTasksClusterService$1.execute(PersistentTasksClusterService.java:135)
	at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:63)
	at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:804)
	at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:378)
	at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:249)
	at org.opensearch.cluster.service.MasterService.access$000(MasterService.java:86)
	at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:173)
	at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:174)
	at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:212)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733)
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:275)
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:238)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ivan32rus** [comment]
+
[2023-12-20T16:08:28,991][ERROR][o.o.r.a.i.TransportReplicateIndexClusterManagerNodeAction] [node02] Failed to trigger replication for logs-vdy-stp-2023.10 - ResourceAlreadyExistsException[task with id {replication:index:logs-vdy-stp-2023.10} already exist]
What should I do?

**Comment by defesteban** [comment]
@soosinha Hi!

Could you explain, why this issue is closed as `completed`? Could you provide PR where this bug is fixed?

**Comment by monusingh-1** [comment]
https://github.com/opensearch-project/cross-cluster-replication/pull/905

**Comment by ivan32rus** [comment]
Hi @monusingh-1   
Thanks for the answer! Do we understand correctly that this error is no longer in Opensearch 2.11. And if our version is 2.3, should it be updated to a more recent one? 
Or is it enough to update the plugin to version 2.11 ?) Thanks!

**Comment by ivan32rus** [comment]
Thank you for addressing this issue! Am I correct that the commit will make it into the 2.11 release?

**Comment by monusingh-1** [comment]
Yes its already part of 2.11 and will be there in future releases as well

**Comment by danielkhatkar** [comment]
@monusingh-1 @ankitkala Is there a way to recover from this on an index without upgrading (planning to)? Through the API? I can't find a way to delete the "replication:index:***" task id.
