### ISSUE TITLE
[BUG]RetentionLeaseInvalidRetainingSeqNoException is coming when retention lease already present on leader for follower index  

### ISSUE THREAD

**Issue by nisgoel-amazon** [opensearch-project/cross-cluster-replication#882]
**What is the bug?**
RetentionLeaseInvalidRetainingSeqNoException is coming when leader cluster is having retention lease and on follower cluster someone try to start replication with same index name.

```
[2023-04-02T22:50:40,816][ERROR][o.o.r.r.RemoteClusterRepository] [4c49dc0e6b723fdade00f0e3b35fe316] Restore of shard from remote cluster repository failed permanently after all retries due to RetentionLeaseInvalidRetainingSeqNoException[the current retention lease with [replication:613844886458:aid-mktplce:[compteamprimary][1]] is retaining a higher sequence number [13301] than the new retaining sequence number [13296] from [replication:613844886458:aid-mktplce]]
    at org.opensearch.index.seqno.ReplicationTracker.renewRetentionLease(ReplicationTracker.java:430)
    at org.opensearch.index.shard.IndexShard.renewRetentionLease(IndexShard.java:2607)
    at org.opensearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:219)
    at org.opensearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:194)
    at org.opensearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.lambda$asyncShardOperation$0(RetentionLeaseActions.java:111)
```

**How can one reproduce the bug?**
1. Create connection between follower and leader domain
2. Start the replication on `index1`
3. Delete the connection between cluster, replication went to autopause and lease on leader will not be deleted as there is no connection.
4. Create the connection again with same alias name
5. Then start the replication of same index after deleting index from follower.

**What is the expected behavior?**
Replication should start successfully without giving RetentionLeaseInvalidRetainingSeqNoException

**What is your host/environment?**
 - OS: linux
 - Version OS-1.3
 - Plugins CCR

**Comment by monusingh-1** [comment]
Closing as resolved
