### ISSUE TITLE
[BUG] Security Integ tests are failing on 2.x due to setup issues

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/cross-cluster-replication#908]
**What is the bug?**
Security Integ tests are failing on 2.x due to setup issues

**How can one reproduce the bug?**
- Check the workflow errors: https://github.com/opensearch-project/cross-cluster-replication/actions/runs/5087351696/jobs/9142646007?pr=657
```
org.opensearch.replication.integ.rest.SecurityCustomRolesIT > classMethod FAILED
Suite: Test class org.opensearch.replication.integ.rest.SecurityCustomRolesIT
    org.opensearch.client.ResponseException: method [PUT], host [https://[::1]:43247], URI [_plugins/_security/api/internalusers/testUser1], status line [HTTP/1.1 400 Bad Request]
  2> org.opensearch.client.ResponseException: method [PUT], host [https://[::1]:43247], URI [_plugins/_security/api/internalusers/testUser1], status line [HTTP/1.1 400 Bad Request]
    {"status":"error","reason":"Weak password"}
    {"status":"error","reason":"Weak password"}
        at __randomizedtesting.SeedInfo.seed([272BE71E3127C24D]:0)
        at __randomizedtesting.SeedInfo.seed([272BE71E3127C24D]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:345)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)

```

**Comment by ps48** [comment]
Hi @saikaranam-amazon, I see that these integ test failure are a blocking SQL build for 2.8 release. Is this still to be worked in 2.9? Also,  2.8 infra autocuts  https://github.com/opensearch-project/cross-cluster-replication/issues/825 https://github.com/opensearch-project/cross-cluster-replication/issues/824 https://github.com/opensearch-project/cross-cluster-replication/issues/843 seem to be related to this.
